# Naive bayes - mushroom dataset

### Load data

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("./../data_sets/mushroom-data/mushrooms.csv")

In [3]:
data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
data.shape

(8124, 23)

### label encoder

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
# apply label encoding on all 
df = data.apply(le.fit_transform)

In [8]:
df.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [9]:
df.describe() 
# as we can see it is a wrong we to pre process(for other algo) but will wotk for niave bayes

class    cap-shape  cap-surface    cap-color      bruises  \
count  8124.000000  8124.000000  8124.000000  8124.000000  8124.000000   
mean      0.482029     3.348104     1.827671     4.504677     0.415559   
std       0.499708     1.604329     1.229873     2.545821     0.492848   
min       0.000000     0.000000     0.000000     0.000000     0.000000   
25%       0.000000     2.000000     0.000000     3.000000     0.000000   
50%       0.000000     3.000000     2.000000     4.000000     0.000000   
75%       1.000000     5.000000     3.000000     8.000000     1.000000   
max       1.000000     5.000000     3.000000     9.000000     1.000000   

              odor  gill-attachment  gill-spacing    gill-size   gill-color  \
count  8124.000000      8124.000000   8124.000000  8124.000000  8124.000000   
mean      4.144756         0.974151      0.161497     0.309207     4.810684   
std       2.103729         0.158695      0.368011     0.462195     3.540359   
min       0.000000         0.000000      0.000000     0.000000     0.000000   
25%       2.000000         1.000000      0.000000     0.000000     2.000000   
50%       5.000000         1.000000      0.000000     0.000000     5.000000   
75%       5.000000         1.000000      0.000000     1.000000     7.000000   
max       8.000000         1.000000      1.000000     1.000000    11.000000   

       ...  stalk-surface-below-ring  stalk-color-above-ring  \
count  ...               8124.000000             8124.000000   
mean   ...                  1.603644                5.816347   
std    ...                  0.675974                1.901747   
min    ...                  0.000000                0.000000   
25%    ...                  1.000000                6.000000   
50%    ...                  2.000000                7.000000   
75%    ...                  2.000000                7.000000   
max    ...                  3.000000                8.000000   

       stalk-color-below-ring  veil-type   veil-color  ring-number  \
count             8124.000000     8124.0  8124.000000  8124.000000   
mean                 5.794682        0.0     1.965534     1.069424   
std                  1.907291        0.0     0.242669     0.271064   
min                  0.000000        0.0     0.000000     0.000000   
25%                  6.000000        0.0     2.000000     1.000000   
50%                  7.000000        0.0     2.000000     1.000000   
75%                  7.000000        0.0     2.000000     1.000000   
max                  8.000000        0.0     3.000000     2.000000   

         ring-type  spore-print-color   population      habitat  
count  8124.000000        8124.000000  8124.000000  8124.000000  
mean      2.291974           3.596750     3.644018     1.508616  
std       1.801672           2.382663     1.252082     1.719975  
min       0.000000           0.000000     0.000000     0.000000  
25%       0.000000           2.000000     3.000000     0.000000  
50%       2.000000           3.000000     4.000000     1.000000  
75%       4.000000           7.000000     4.000000     2.000000  
max       4.000000           8.000000     5.000000     6.000000  

[8 rows x 23 columns]

In [10]:
X = df.iloc[:,1:].values
y = df.iloc[:,0].values

### Train test split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [12]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(6499, 22)
(6499,)
(1625, 22)
(1625,)


In [13]:
# feature vector
print(X_train[:5,:])

[[3 2 2 0 7 1 0 1 0 1 0 2 1 6 7 0 2 1 0 7 4 0]
 [5 2 4 0 2 1 0 1 0 1 0 1 2 7 7 0 2 1 0 7 4 4]
 [2 3 2 0 8 1 0 1 0 1 0 2 2 6 7 0 2 1 0 7 4 2]
 [2 0 4 1 5 1 0 0 9 1 1 2 2 3 6 0 2 1 4 3 4 0]
 [0 3 9 1 3 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 3]]


In [14]:
print(np.unique(y_train))

[0 1]


### Building the classifier

#### prior probability

In [15]:
def prior_prob(y_train,label):
    numerator = np.sum(y_train==label)
    denominator = y_train.shape[0]
    return (numerator)/float(denominator)

#### Likelihood / prosterior prob

In [16]:
def likelihood(X_train,y_train,column,column_value,label):
    X_filtered = X_train[y_train==label]
    numerator = np.sum(X_filtered[:,column]==column_value)
    denominator = np.sum(y_train==label)
    return (numerator)/float(denominator)

#### predict

In [17]:
def predict(X_train,y_train,X_test):
    prosterior_prob = []
    lables = np.unique(y_train)
    for label in lables:
        likeli = 1.0
        prior = prior_prob(y_train,label)
        for feature in range(len(X_test)): 
            cond = likelihood(X_train,y_train,feature,X_test[feature],label)
            if cond==0: 
                continue
            likeli *= cond
        prost_prob = prior*likeli
        prosterior_prob.append(prost_prob)
    return np.argmax(prosterior_prob)

In [18]:
print(predict(X_train,y_train,X_test[4]))
print(y_test[4])

1
1


In [19]:
def score(X_train,y_train,X_test,y_test):
    y_pred = []
    for x in range(X_test.shape[0]):
        pred = predict(X_train,y_train,X_test[x])
        y_pred.append(pred)
    return (np.sum(y_pred==y_test))/y_test.shape[0]
        
    

In [20]:
score(X_train,y_train,X_test,y_test)

0.8387692307692308