# Numpy

In [1]:
import numpy as np

In [7]:
# array
a = np.array([[1],[2],[3],[4],[5]])
a

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [8]:
# type
print(type(a))

<class 'numpy.ndarray'>


In [9]:
# shape
a.shape

(5, 1)

In [11]:
# indexing
a[0][0] # (2d)

1

In [13]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
print(b.shape)
print(type(b))
print(b[0][0])

(2, 3)
<class 'numpy.ndarray'>
1


In [39]:
# create zeros,ones
a = np.zeros((3,3))
print(a)
b = np.ones((2,3),dtype=np.int64)
print(b)
c = np.full((3,2),5)
print(c)
d = np.eye(4)
print(d)
e = np.random.random((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1]
 [1 1 1]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.99141793 0.50268148 0.44192741]
 [0.67864007 0.54766718 0.93678387]]


In [40]:
# slicing
print(e[:,1:2])
print()
print(e[-1,1:3])

[[0.50268148]
 [0.54766718]]

[0.54766718 0.93678387]


In [41]:
# datatypes
print(b.dtype)
b.dtype = np.int64
print(b.dtype)

int64
int64


In [43]:
# matrix operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[6,7,8]])

In [44]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.dot(a.T,b))

[[ 4  6  8]
 [10 12 14]]
[[-2 -2 -2]
 [-2 -2 -2]]
[[ 3  8 15]
 [24 35 48]]
[[27 32 37]
 [36 43 50]
 [45 54 63]]


In [61]:
# stacking
print(np.hstack((a,b)).shape)
print(np.vstack((a,b)).shape)
print(np.stack((a,b),axis=1).shape)
print(np.stack((a,b),axis=0).shape)

(2, 6)
(4, 3)
(2, 2, 3)
(2, 2, 3)


In [63]:
# reshape
a.reshape((6,-1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [64]:
a.reshape((-1,6))

array([[1, 2, 3, 4, 5, 6]])

## Numpy random module

In [80]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [82]:
# shuffle
np.random.shuffle(a)
a

array([10,  5, 12, 13,  8,  9,  7, 11, 14,  6])

In [83]:
# random numbers from a standard normal distributions
a = np.random.randn(2,3)
print(a)

[[-0.61194628 -0.46233148  0.42955069]
 [ 0.23264518  1.9959624  -0.30161134]]


In [84]:
# random integers in a given range
a = np.random.randint(1,10,(2,3))
print(a)

[[6 6 2]
 [5 6 1]]


In [85]:
# random choice
np.random.seed(6) # to replicate the results 
a = np.random.choice([1,2,3,4,5,6])
print(a)

3


In [87]:
# a[np.where((a >= 5) & (a <= 10))]

# a[(a >= 5) & (a <= 10)]

# a[np.all((a >= 5) & (a <= 10))]

# a[np.any((a >= 5) & (a <= 10))]

## Numpy statistic functions
- min,max
- mean
- median
- average
- variance
- standard deviation

In [93]:

a = np.array([[1,2,3,4],[5,6,7,8]])
# mean
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

# min
print(np.min(a,axis=0))
print(np.min(a,axis=1))

# max
print(np.max(a,axis=0))
print(np.max(a,axis=1))

[3. 4. 5. 6.]
[2.5 6.5]
[1 2 3 4]
[1 5]
[5 6 7 8]
[4 8]


In [94]:
# middle most value
print(np.median(a,axis=0))
print(np.median(a,axis=1))

[3. 4. 5. 6.]
[2.5 6.5]


In [98]:
# average  ( weighted )
b = np.array([1,2,3,4])
print(np.average(b,weights=b))
print(np.average(b,weights=[1,1,1,1]))
print(np.mean(b))

3.0
2.5
2.5


In [103]:
# standard deviation
print(np.std(b))
print(np.sqrt(np.mean(abs(b-(np.mean(b)))**2)))
# variance
print(np.var(b))

1.118033988749895
1.118033988749895
1.25
